name: iptv_player_mvp
description: Aplicativo IPTV com login e player Flutter
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.4
  device_info_plus: ^10.1.0
  network_info_plus: ^5.0.3
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
